# This is a basic workflow to help you get started with Actions

name: print echo jq

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  print:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      # Runs a single command using the runners shell
      - id: login
        name: login
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
          LOGIN=$(curl -s -X GET -G $URL | jq -r '.user.login')
          echo ::set-output name=login::$LOGIN
      - id: files
        name: files
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename, .status')
          echo $FILES
          echo $login
        env:
          login: ${{ steps.login.outputs.login }}
      - id: automerge
        name: automerge
        needs: files
        uses: pascalgn/automerge-action@v0.12.0
        env:
          MERGE_LABELS: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          USER_LOGIN: ${{ github.event.pull_request.user.login }}
        run: echo "$USER_LOGIN"
