name: Automerge
description: Check for automerge
on:
  # Improvements for public repository forks
  # new `pull_request_target` event
  # https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
  pull_request_target:
    # By default workflow runs on `opened` type 
    branches: [ main ]
# A workflow run is made up of one or more jobs
# They can run sequentially or in parallel
jobs:
  main:
    name: Automerge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Pass output between steps
      - # Syntax is ::set-output name=< var name >::< var value >
        id: set_output
        name: Set output
        run: echo ::set-output name=var_name::example_value
      - # Syntax is env: < var name >: ${{ steps.< step.id >.outputs.< var name > }}
        id: get_output
        name: Get output
        env:
          var: ${{ steps.set_output.outputs.var_name }}
        run: echo $var
      - # Curl pull request files
        id: files
        name: files
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[]')
          file_number=${#FILES[@]}
          echo "number of files: ${#FILES[@]} ${file_number}"
          filename=$(echo $FILES | jq '.filename')
          echo "filename: $filename"
          status=$(echo $FILES | jq '.status')
          echo "status: $status"
          echo "github.actor: ${{ github.actor }}"
      - name: exit success
        run: exit 0
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump github.event.pull_request object
        run: |
          echo "github.event.pull_request.changed_files: ${{ github.event.pull_request.changed_files }}"
          echo "github.event.pull_request.additions: ${{ github.event.pull_request.additions }}"
          echo "github.event.pull_request.deletions: ${{ github.event.pull_request.deletions }}"
          echo "github.event.pull_request.author_association: ${{ github.event.pull_request.author_association }}"
          echo "github.event.pull_request.head.repo.full_name: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "github.event.pull_request.head.repo.fork: ${{ github.event.pull_request.head.repo.fork }}"
      - id: automerge
        name: automerge
        # none of the previous steps have failed
        if: success()
        uses: pascalgn/automerge-action@v0.12.0
        env:
          MERGE_LABELS: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
